[project]
name = "stacks-exchange"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.sip-010-trait-ft-standard-v2-c4]
path = "contracts/traits/sip-010-trait-c4.clar"
epoch = "latest"

[contracts.token-x-c4]
path = "contracts/test-tokens/token-x-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.token-y-c4]
path = "contracts/test-tokens/token-y-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.pool-c4]
path = "contracts/pool-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.pool-v-c4]
path = "contracts/pool-v-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.pool-v2-c4]
path = "contracts/pool-v2-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.pool-v3-c4]
path = "contracts/pool-v3-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.pool-v4-c4]
path = "contracts/pool-v4-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.pool-v5-c4]
path = "contracts/pool-v5-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[contracts.pool-lp-c4]
path = "contracts/pool-lp-c4.clar"
depends_on = ["sip-010-trait-ft-standard-v2-c4"]
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet


